import type { Locale } from "./types";
const en = {
  demo: "Book a Workflow Demo",
  platform: "Explore the Platform",
  applications: "Explore the Applications",
  nav: [
    "Home",
    "Platform",
    "Applications",
    "AI",
    "Workflows",
    "Why VirSME",
    "Resources",
    "Pricing",
  ],
  pageNames: [
    "Home",
    "Platform",
    "Applications",
    "Connect",
    "People",
    "Work",
    "Sales",
    "VirSME AI",
    "Workflows",
    "Implementation",
    "Why VirSME",
    "Pricing",
    "Ecosystem",
    "About",
    "VirSME Facts",
    "Book a Workflow Demo",
    "Resources",
  ],
  groups: ["Product", "Company", "Resources", "Legal"],
  legal: ["Privacy", "Terms", "Cookie notice"],
  legalPending: "Legal information is being prepared for publication.",
  close: "Close",
  menu: "Open navigation",
  navigation: "Main navigation",
  breadcrumb: "Breadcrumb",
  skip: "Skip to content",
  home: "VirSME home",
  language: "العربية",
  languageLabel: "Switch to Arabic",
  category: "AI-native Business Operating System for SMEs",
  tagline: "One operating environment. Connected by design.",
  concept: "Conceptual operating model",
  foundation: "Shared operating foundation",
  connected: "One connected operating environment",
  ai: "Intelligence across the business",
  context: "Business context",
  process: "Processes and SOPs",
  controls: "Policies and controls",
  authority: "Roles and authority",
  modules: [
    "Communication & collaboration",
    "HCM & workforce operations",
    "Work & operational execution",
    "Full CRM & customer operations",
  ],
  established: "Established today",
  roadmap: "Future direction",
  approval: "Human authorization",
  event: "Business event",
  completed: "Completion & audit trail",
  workflow: "A connected workflow",
  steps: ["Employee record", "Apply the SOP", "Assign work", "Notify the team"],
  salesSteps: [
    "Won opportunity",
    "Customer context",
    "Delivery ownership",
    "Team handoff",
  ],
  requestSteps: [
    "Customer request",
    "Applicable SOP",
    "Required actions",
    "Authorized completion",
  ],
  approvalSteps: [
    "Business request",
    "Policy & threshold",
    "Authorized person",
    "Recorded decision",
  ],
  factsDate: "September 2026",
  updated: "Last updated",
  source:
    "Source: Salesforce, Small & Medium Business Trends Report, 6th Edition",
  stats: [
    "Business applications used on average",
    "Report inconsistent data across tools",
    "Feel overwhelmed by too many tools",
    "Lack time to master their technology",
  ],
  soon: "Coming soon",
  upcoming: "Upcoming guides",
  notFound: "This page could not be found.",
  backHome: "Return to Home",
  formTitle: "Let’s start with your workflow.",
  formIntro: "Tell us about your business and the process you want to improve.",
  fields: [
    "Name",
    "Company",
    "Work email",
    "Phone / WhatsApp",
    "Country",
    "Number of employees",
    "Workflow you want to improve",
    "Tools involved today",
    "Preferred language",
    "Preferred meeting time",
  ],
  required: "Required",
  optional: "Optional",
  select: "Select an option",
  languages: ["English", "Arabic"],
  employeeOptions: ["1–10", "11–50", "51–200", "201–500", "501+"],
  submit: "Book a Workflow Demo",
  sending: "Sending your request…",
  successTitle: "Your request has been received.",
  success: "Thank you. Your workflow demo request was delivered successfully.",
  errorRequired: "Please complete this field.",
  errorEmail: "Enter a valid work email address.",
  errorLength: "Please shorten this response.",
  errorNumber: "Select a valid employee range.",
  errorGeneral: "We could not send your request. Please try again.",
  errorUnavailable:
    "Demo booking is temporarily unavailable. Please try again later.",
  errorSpam: "Please wait a moment and try again.",
  errorsTitle: "Please check the highlighted fields.",
  honeypot: "Leave this field empty",
  footerNote: "AI-native Business Operating System for SMEs",
  copyright: "VirSME",
  viewModule: "Explore",
  aiExplore: "Explore VirSME AI",
  seeWorkflows: "See How Workflows Connect",
  next: "Explore the operating environment",
};
type Ui = typeof en;
const ar: Ui = {
  demo: "احجز عرضا لسير العمل",
  platform: "استكشف المنصة",
  applications: "استكشف التطبيقات",
  nav: [
    "الرئيسية",
    "المنصة",
    "التطبيقات",
    "الذكاء الاصطناعي",
    "سير العمل",
    "لماذا VirSME؟",
    "الموارد",
    "الأسعار",
  ],
  pageNames: [
    "الرئيسية",
    "المنصة",
    "التطبيقات",
    "Connect",
    "People",
    "Work",
    "Sales",
    "VirSME AI",
    "سير العمل",
    "التنفيذ والانضمام",
    "لماذا VirSME؟",
    "الأسعار",
    "المنظومة",
    "عن VirSME",
    "حقائق VirSME",
    "احجز عرضا لسير العمل",
    "الموارد",
  ],
  groups: ["المنتج", "الشركة", "الموارد", "الشؤون القانونية"],
  legal: ["الخصوصية", "الشروط", "إشعار ملفات الارتباط"],
  legalPending: "يجري إعداد المعلومات القانونية للنشر.",
  close: "إغلاق",
  menu: "فتح القائمة",
  navigation: "التنقل الرئيسي",
  breadcrumb: "مسار التنقل",
  skip: "انتقل إلى المحتوى",
  home: "الرئيسية VirSME",
  language: "English",
  languageLabel: "Switch to English",
  category: "نظام تشغيل أعمال بالذكاء الاصطناعي للمنشآت الصغيرة والمتوسطة",
  tagline: "بيئة تشغيل واحدة. مترابطة بالتصميم.",
  concept: "تصور للنموذج التشغيلي",
  foundation: "أساس تشغيلي مشترك",
  connected: "بيئة تشغيل واحدة مترابطة",
  ai: "الذكاء عبر المنشأة",
  context: "سياق الأعمال",
  process: "العمليات وإجراءات التشغيل",
  controls: "السياسات والضوابط",
  authority: "الأدوار والصلاحيات",
  modules: [
    "التواصل والتعاون",
    "HCM وعمليات القوى العاملة",
    "العمل والتنفيذ التشغيلي",
    "CRM متكامل وعمليات العملاء",
  ],
  established: "الراسخ اليوم",
  roadmap: "اتجاه المستقبل",
  approval: "الموافقة البشرية",
  event: "حدث أعمال",
  completed: "الإكمال وسجل التدقيق",
  workflow: "سير عمل مترابط",
  steps: ["سجل الموظف", "تطبيق الإجراءات", "توزيع العمل", "إشعار الفريق"],
  salesSteps: [
    "فرصة رابحة",
    "سياق العميل",
    "مسؤولية التنفيذ",
    "التسليم للفريق",
  ],
  requestSteps: [
    "طلب العميل",
    "الإجراء المطبق",
    "الإجراءات المطلوبة",
    "الإكمال المصرح به",
  ],
  approvalSteps: [
    "طلب أعمال",
    "السياسة والحدود",
    "الشخص المخول",
    "تسجيل القرار",
  ],
  factsDate: "سبتمبر 2026",
  updated: "آخر تحديث",
  source:
    "المصدر: Salesforce، تقرير اتجاهات المنشآت الصغيرة والمتوسطة، الإصدار السادس",
  stats: [
    "متوسط عدد تطبيقات الأعمال",
    "بيانات غير متسقة عبر الأدوات",
    "يشعرون بالإرهاق من كثرة الأدوات",
    "لا يملكون الوقت لإتقان التقنية",
  ],
  soon: "قريبا",
  upcoming: "إرشادات قادمة",
  notFound: "تعذر العثور على هذه الصفحة.",
  backHome: "العودة إلى الرئيسية",
  formTitle: "لنبدأ بسير العمل.",
  formIntro: "أخبرنا عن منشأتك والعملية التي تريد تحسينها.",
  fields: [
    "الاسم",
    "الشركة",
    "البريد الإلكتروني للعمل",
    "الهاتف / WhatsApp",
    "الدولة",
    "عدد الموظفين",
    "سير العمل الذي تريد تحسينه",
    "الأدوات المستخدمة اليوم",
    "اللغة المفضلة",
    "موعد الاجتماع المفضل",
  ],
  required: "مطلوب",
  optional: "اختياري",
  select: "اختر",
  languages: ["English", "العربية"],
  employeeOptions: ["1–10", "11–50", "51–200", "201–500", "501+"],
  submit: "احجز عرضا لسير العمل",
  sending: "جار إرسال الطلب…",
  successTitle: "تم استلام طلبك.",
  success: "شكرا لك. تم إرسال طلب عرض سير العمل بنجاح.",
  errorRequired: "يرجى إكمال هذا الحقل.",
  errorEmail: "أدخل بريدا إلكترونيا صالحا للعمل.",
  errorLength: "يرجى اختصار الإجابة.",
  errorNumber: "اختر نطاقا صالحا لعدد الموظفين.",
  errorGeneral: "تعذر إرسال طلبك. يرجى المحاولة مجددا.",
  errorUnavailable: "حجز العروض غير متاح مؤقتا. يرجى المحاولة لاحقا.",
  errorSpam: "يرجى الانتظار قليلا والمحاولة مجددا.",
  errorsTitle: "يرجى مراجعة الحقول المحددة.",
  honeypot: "اترك هذا الحقل فارغا",
  footerNote: "نظام تشغيل أعمال بالذكاء الاصطناعي للمنشآت الصغيرة والمتوسطة",
  copyright: "VirSME",
  viewModule: "استكشف",
  aiExplore: "استكشف VirSME AI",
  seeWorkflows: "استكشف سير العمل",
  next: "استكشف بيئة التشغيل",
};
export const ui = (locale: Locale): Ui => (locale === "ar" ? ar : en);
